name: Scheduled X Bot

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  run-twitter-bot:
    runs-on: ubuntu-latest

    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Twitter Bot
        run: python bot/main.py
